{% set name = "pycocotools" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c06e73a85ed9874c1174d47064524b9fb2759b95a6997437775652f20c1711f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - matplotlib-base
  run:
    - python
    - cython
    - matplotlib-base

test:
  imports:
    - pycocotools
    - pycocotools.mask
    #- pycocotools.coco
    #- pycocotools.cocoeval

about:
  home: https://github.com/cocodataset/cocoapi
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.txt
  summary: Library to work with COCO dataset.
  doc_url: http://cocodataset.org
  dev_url: https://github.com/cocodataset/cocoapi

extra:
  recipe-maintainers:
    - hadim
