appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: rLhIigBcdux523MYqj9rrdMyk17IGTeLeeI2JVpUmm8QpZ7w/JY5GR444JSHSZe6eoAfrAik8nCnWx2s2a36ndeHd4or/QoMbOQMH7O1zNDVHMi408139dH2GDNwRCwLy4U4YcSYRDZ5p3yw3UnvdopoBeBzNDZ+u8RwlUU2wMNriSRdWVEgyYA7cgSkLgFnUcq1/7yUtp9FNiYXaVktme+QpNJUBmfPK1fn+HDiQnJZMhbK3/qDWFNQKu3I/TovTf3bsMXJArF0ZQYiheAMYsiSDINtmZTy5iNt18Co7D4E9HWa/gkuJ/lopX9K6nEtX8eseBq4kI4UjafN3OMWGutGM7ZtdMUkxkYJB/T/MKvpRN84YXGjUwivBmGXwpbf/XSYBK9WVy0fI3rmba8nD2+kW0fcTp2YHFA6x8iLR+JtlGjzZKzarHr6UbUILL2bKsX9BFeQ4flfcX4j0M5WcRCXZrHCXlK1XZMd6vZNrwSbS03teBdtMqmqqakSfmEHvrb34CTpT1uHbqQbXeJ7hJ5W2Ql0B7JUBiti9+3KQL8E0L0mb1178Z7KKN2G3AQ8re4iE5qrPSvHe8qdeacWbsSokvyOkDMA+ctb+ptFHfOrni9i/LfkwKohilxiusA3tLSxMw8gMXYYQe84Sg6ZQQviOgETggUOPS8Fg874JyY=}
