travis:
  secure:
    BINSTAR_TOKEN: zaG84FWW1Omzl1Jzrfsdg73qTRss178xED+dTr0Quiymyup3Qgp3A+b3ItcjWateglzKZCJquzncW307HvckBuACTiCRTzMsWmSwjSDksmwe44yrCttugX1BdpclRc/t7NHrEYrSTLsfA/OQE067Fc94W4rbDGqu7XnWyYqqTTe3ALhHKjIHzH3lihyipSsptTyQaq7Vm8D4wf4bN1mzcXVMtLRSzfdj6QnmDuIUPNF/DV/mc2561qW+YqqWO3H7Z/WcqscZclS//XoFfKa/tR6lYeaP4igoT1JTY6nzPXGHOFV6wYQ8IxZdNTkA5YQ8dCq3YuFDwpV/lOjRXeOEYh9HCQd4+i/KxPSShhpwne+JIEPiYz+gBPXz8p3BIH7kQh2ojLd9HvJruWOaLmCZSP7/6XoEmFcWkW8B0UfS+4YPr6Q+haXZCvLF7zqEbvvDwT3wHcj85BaiQ1nbnm1d4opBtut4SAsSDp1uz2yQLCO5+uEVQTkf2dY5I2NGUaKl4MbczowDq0CTVtOPPCUQE2y5qBlvscn0iYJXj3D10G/aia72yxppWu8+kBmaTOyxZ/Ihjue/coq7JkBIqIHeKD/XIaAD7gt25t25Kd1Qf6KZUVy5b03e8xnwcu2/QfPIISq6Rg5P04Azq+Lf1nolDzdH7m0av+fh7FvZBE7H0D4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
